# Generated by Django 3.2.5 on 2021-12-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meme',
        ),
    ]
