# Generated by Django 3.2.5 on 2021-12-21 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memes', '0006_meme_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.ManyToManyField(related_name='memes', to=settings.AUTH_USER_MODEL),
        ),
    ]
