# Generated by Django 3.2.5 on 2021-12-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0007_meme_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='updated_at',
        ),
    ]
